### ISSUE TITLE
Feedback on README 15-09-2016

### ISSUE THREAD

**Issue by martinmosegaard** [Praqma/RSS#2]
- Pipeline: For some projects, it may be easier to use Travis rather than our internal Jenkins.
- How do we get subpages on code.praqma.com? And which projects should have that - it probably doesn't apply to all?
- My guess is only a few projects will need their own site (like 2git.io)
- If MIT license has been chosen as the standard, we should describe why. 

In that sense, I read some of the points on the README as suggestions. For example also logo - you could have that if it is a product and it makes sense. You could also have badges, like Travis build status, code coverage, etc. But it depends on the nature of the repository.

**Comment by sofusalbertsen** [comment]
Totally right @martinmosegaard. As I've tried to state in the README of this repo, it's an opt-out standard, where you need to argue why it is not applicable to your repo. 
And noted with travis. But how do we impliment our Phlow in travis?

**Comment by martinmosegaard** [comment]
I don't know how you would do pretested integration in Travis. But it just integrates very easily with GitHub and is a fast way to setup CI. A Jenkins pipeline is essential for some of our repos, like the websites and Jenkins plugins. But it is probably too much for POCs.

**Comment by sofusalbertsen** [comment]
@martinmosegaard could I ask you to describe that in the readme? When is one prefered over the other etc?

**Comment by martinmosegaard** [comment]
Yes, will do.
