### ISSUE TITLE
Can we rename the repo please?

### ISSUE THREAD

**Issue by martinmosegaard** [Praqma/RSS#4]
RSS is ambiguous in favor of the feed thingy.

Here are few suggestions:
- repository-standards
- praqma-repository-standards
- same, but just as "repo"
- guidelines
- norms
- code-yardstick
- code-code

**Comment by martinmosegaard** [comment]
Also, lowercase, please.

**Comment by buep** [comment]
don't spend to much time on new name, I think the writing in this RSS repo belongs somewhere else.... might not be the handbook, but the technical counterpart of such ... or similar.

See my other issue, about that they do not belong anywhere, except from in a configuration file that is used with our check-standards-script. See #6

**Comment by lakruzz** [comment]
I chose "repository-standards" - Done!

**Comment by lakruzz** [comment]
...The old name RSS still redirects to the new one, so it doesn't really break anything.
